### ISSUE TITLE
Compatibility with three.js r78

### ISSUE THREAD

**Issue by boisgera** [unconed/threestrap#7]
Hi !

Would an update of the code to keep up with the evolution of three.js be welcome ?
Has the compatibility been tested?

There is at least one issue that I am aware of: in the `EventDispatcher` class that comes from three.js, 
the `apply` method that was used to mix-in the event methods into any object has been removed
(actually, you could do the job with Object.assign, you don't need an extra method for that).

Threestrap uses this `apply` method, but this is a one-liner that could easily get fixed. 
(the `Binder` actually defines its own `apply` method with the same meaning of "let's mix stuff in")

Cheers,

SB

**Comment by unconed** [comment]
Sure, that would be good. Compatibility shouldn't be an issue, Threestrap doesn't do a whole lot by itself, but I haven't verified it myself.

**Comment by boisgera** [comment]
Hi Steven,

I just noticed that there is already an attempt (a pull request) to use three.js latest automatically,
but there is no patch for the source code, so it won't work out of the box AFAICT (because of the change in the three.js API).

**Comment by sritchie** [comment]
Closing this since I will cover it with the next merge to master.
